### ISSUE TITLE
Pls update this !

### ISSUE THREAD

**Issue by sonderlau** [Zamirathe/ZaupFeast#11] opened 2015-08-18 09:38 UTC
All the mates all waiting ur plugin...   We cant use this on the Newest Version.... pls !!!   Be a superman!!

**Comment by Zamirathe** [comment] 2015-08-18 19:52
What do you mean by it can't be used on the newest version?  It doesn't help me to determine what the issue is.

**Comment by Solenus** [comment] 2015-08-19 00:34
If you read the other issue reports, you'd see. I know you said you don't check the rocket foundation website for comments either, but you might want to reconsider that because there's been a lot of chat there about it. 

Basically, we're all getting an error where instead of "The feast will be arriving in X minutes at Y" we're getting coming_feast_msg printed out instead. Also, doesn't seem like anyone (me included) can figure out how to make custom feast messages since you change it to support the plane model for skydrops.

**Comment by Zamirathe** [comment] 2015-08-20 01:22
I had already answered it over on the rocket site on the 4th of August.  As I stated there, I am not able to replicate the issue with the chat messages not showing up.  Use the translation file.

https://rocket.foundation/viewtopic.php?f=17&t=561&start=10#p2966

And please don't assume that because I didn't close the issue or respond to it means I didn't read it.  Do a little more looking into the forums on the rocket site next time.  You would've found what I did in a matter of minutes.

**Closed as completed by Zamirathe** 2015-08-20 01:22 UTC
Labels: invalid

**Comment by Evident-Dev** [comment] 2015-08-21 03:09
Works for me Zami ;) Sounds like he needs to delete his config and translation file and start fresh.
